### ISSUE TITLE
Bug (calculating det. bug)

### ISSUE THREAD

**Issue by AliBadawy** [AliBadawy/Matrix-Project#1]
#####(A/B)
The result isn't correct

**Comment by AliBadawy** [comment]
during calculating the det(B) it returns random incorrect answers .

**Comment by AliBadawy** [comment]
the calculating Algorithm is checked and it's right .

**Comment by AliBadawy** [comment]
the calculating Algorithm is rechecked and a bug discovered.

**Comment by adelmaek** [comment]
Determinant function had an impractical run time using the normal recursive algorithm,
problem is solved using another algorithm called Gaussian elimination algorithm, it works with the elementary matrix operations to calculate the determinant.
when calculating inverse matrix , it worked well with the "example.m" file but , it didn't get right values for all elements in the "bigexample.m" file.
by printing the Matrix after every elementary operation while calculating determinant using Gaussian algorithm, it was found the algorithm was working well , but those procedure didn't calculate the same result as that calculated using Matlab.

**Comment by adelmaek** [comment]
Bug solved A/B gives same result as that given by Matlab on executing both "bigexample.m" and "example.m".
