### ISSUE TITLE
Handle errors 

### ISSUE THREAD

**Issue by adelmaek** [AliBadawy/Matrix-Project#10]
A = [1 2; 1 2 3]
B = [1 C; 1 2 3] where C =1
A = [1 2; 3]
B = 5 / 0
C = 3 * (2 + 4 + 
interactive response as required in errors examples file

**Comment by OthmanMohamed** [comment]
handling errors in multioperatios function
ex:
(4-5+
no closed bracket, no second operand after the +

**Comment by adelmaek** [comment]
![image](https://user-images.githubusercontent.com/33881557/35480680-5171da62-041c-11e8-8f35-ff633cb9207d.png)

**Comment by adelmaek** [comment]
![image](https://user-images.githubusercontent.com/33881557/35480688-7c8d5870-041c-11e8-8b99-05b6c0a25c66.png)
