### ISSUE TITLE
Accepting inputs in multilines

### ISSUE THREAD

**Issue by adelmaek** [AliBadawy/Matrix-Project#13]

**Comment by 3omar3allam** [comment]
if(newEntry)cout << ">> ";

    else cout<<"\t";

    string line = "";

    static string temp = "";

    getline(cin, line, '\n');

    static int openBrackets = 0, closeBrackets = 0;

    /** Detect Multi-line Commands **/

    for (size_t i = 0; i<line.length(); i++) {

        if (line[i] == '[')openBrackets++;

       else if (line[i] == ']')closeBrackets++;

    }

    while (line.find("\r") != line.npos)line.erase(line.find("\r"), 1);

    while (line.find("\n") != line.npos)line.erase(line.find("\n"), 1);

    if (openBrackets>closeBrackets) {  //command haven't ended yet

        temp += line;

        if(line[line.length()-1] == ';');

            else temp += ";";

            newEntry=false;

            continue;

        }

        else {

            openBrackets = 0, closeBrackets = 0;

            commandLine = temp + line;

            temp = "";

            newEntry = true;

        }
